import Add from '../assets/add.png'
import Administrator from '../assets/admin.png'
import Arrow from '../assets/arrow-icon.svg'
import BackArrow from '../assets/backarrow.svg'
import Completed from '../assets/completada.png'
import Confetti from '../assets/confeti.png'
import Correct from '../assets/correct.png'
import Delete from '../assets/delete.png'
import Hello from '../assets/hello.png'
import Home from './Home.svg'
import Incorrecta from '../assets/incorrecta.png'
import Info from '../assets/info.svg'
import Logo from '../assets/logo.png'
import Pencil from '../assets/pencil.png'
import Profiles from '../assets/profile.png'
import Rain from '../assets/rain.png'
import User from '../assets/user.svg'

export {Add, Administrator, Arrow, BackArrow, Completed, Confetti, Correct, Delete, Hello, Home, Incorrecta, Info, Logo, Pencil, Profiles, Rain, User}